# .github/workflows/ci.yml
name: CI (Lint & Tests)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Set the default working directory for all run: steps
defaults:
  run:
    # Change this to your actual code folder, e.g. "backend" or "2025-ma-bishwo-bijaya-shah"
    working-directory: ./

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install --cache-dir ~/.cache/pip -r requirements.txt
          fi
          pip install ruff pytest

      - name: Ruff lint
        run: |
          ruff check src

      - name: Ruff format-check
        run: |
          ruff format --check src

      - name: Run pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q
